apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: route-topic
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: ROUTE